version: "3.9"

services:
  terraform:
    image: cmdlabs/terraform-utils:11.0.1
    environment:
      - AWS_SDK_LOAD_CONFIG=1
      - AWS_PROFILE="${AWS_PROFILE}"
      - AWS_REGION="${AWS_REGION}"
    entrypoint: []
    volumes:
      - .:/work
      - ~/.ssh:/root/.ssh
    working_dir: /work/${SUBFOLDER}
